# Created using wingetcreate 0.4.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: HCAuditor.NinjaRMM
PackageVersion: 5.2.2265.0
PackageLocale: en-US
Publisher: NinjaRMM LLC
PackageName: NinjaRMMAgent
License: License
ShortDescription: NinjaRMM Installer
ManifestType: defaultLocale
ManifestVersion: 1.0.0

